properties:
  id: products--nmh
  name: Products
  inputDatasets:
    - datasetId: products--nlb
      name: Products
      projectId: '{{project.Migration$_$Source_p_for_cross.projectId}}'
      taskId: transform--nk9
    - datasetId: categories--nlf
      name: Categories
      projectId: '{{project.Migration$_$Source_p_for_cross.projectId}}'
      taskId: transform--nk9
  datasetAttributes:
    materialized: ON
    hasStandardViewsWithHeaders: ON
  tableDef:
    name: Products
    columns:
      - name: ProductID
        ordinal: 1
        nullable: true
        primaryKeyOrdinal: 1
        datatype:
          type: INT4
          originalTypeFull: INTEGER
        id: productid
        properties:
          documentMetadata: true
      - name: ProductName
        ordinal: 2
        nullable: true
        datatype:
          type: WSTRING
          length: 40
          originalTypeFull: NVARCHAR(40)
        id: productname
        properties:
          documentMetadata: true
      - name: SupplierID
        ordinal: 3
        nullable: true
        datatype:
          type: INT4
          originalTypeFull: INTEGER
        id: supplierid
        properties:
          documentMetadata: false
      - name: CategoryID
        ordinal: 4
        nullable: true
        datatype:
          type: INT4
          originalTypeFull: INTEGER
        id: categoryid
        properties:
          documentMetadata: false
      - name: QuantityPerUnit
        ordinal: 5
        nullable: true
        datatype:
          type: WSTRING
          length: 20
          originalTypeFull: NVARCHAR(20)
        id: quantityperunit
        properties:
          documentMetadata: false
      - name: UnitPrice
        ordinal: 6
        nullable: true
        datatype:
          type: NUMERIC
          precision: 19
          scale: 4
          originalTypeFull: NUMBER(19,4)
        id: unitprice
        properties:
          documentMetadata: false
      - name: UnitsInStock
        ordinal: 7
        nullable: true
        datatype:
          type: INT2
          originalTypeFull: SMALLINT
        id: unitsinstock
        properties:
          documentMetadata: false
      - name: UnitsOnOrder
        ordinal: 8
        nullable: true
        datatype:
          type: INT2
          originalTypeFull: SMALLINT
        id: unitsonorder
        properties:
          documentMetadata: false
      - name: ReorderLevel
        ordinal: 9
        nullable: true
        datatype:
          type: INT2
          originalTypeFull: SMALLINT
        id: reorderlevel
        properties:
          documentMetadata: false
      - name: Discontinued
        ordinal: 10
        nullable: true
        datatype:
          type: BOOLEAN
          originalTypeFull: BOOLEAN
        id: discontinued
        properties:
          documentMetadata: false
      - name: CategoryName
        ordinal: 11
        nullable: true
        datatype:
          type: WSTRING
          length: 15
          originalTypeFull: NVARCHAR(15)
        id: products_categories_relation--nlt$_$categoryname
        properties:
          documentMetadata: false
      - name: Description
        ordinal: 12
        nullable: true
        datatype:
          type: NCLOB
          length: 1073741823
          originalTypeFull: NVARCHAR(8388608)
        id: products_categories_relation--nlt$_$description
        properties:
          documentMetadata: false
      - name: Picture
        ordinal: 13
        nullable: true
        datatype:
          type: BLOB
          length: 2147483647
          originalTypeFull: BINARY(8388608)
        id: products_categories_relation--nlt$_$picture
        properties:
          documentMetadata: false
    entityId: ''
  documentDataEntitySettings:
    repeatedDataEntities: []
    type: TYPE1
    rootDataEntityId:
      type: NONE
      datasetId: products--nlb
      name: Products
      projectId: '{{project.Migration$_$Source_p_for_cross.projectId}}'
      taskId: transform--nk9
    entityRelationshipPath:
      - products_categories_relation--nlt
    mapping:
      columns:
        - columnName: ProductID
          type: ROOT_PK
          expression:
            expressionStatement: ${ProductID}
            alias:
              - name: ProductID
                value: ProductID
        - columnName: ProductName
          type: NONE
          expression:
            expressionStatement: ${ProductName}
            alias:
              - name: ProductName
                value: ProductName
        - columnName: SupplierID
          type: NONE
          expression:
            expressionStatement: ${SupplierID}
            alias:
              - name: SupplierID
                value: SupplierID
        - columnName: CategoryID
          type: NONE
          expression:
            expressionStatement: ${CategoryID}
            alias:
              - name: CategoryID
                value: CategoryID
        - columnName: QuantityPerUnit
          type: NONE
          expression:
            expressionStatement: ${QuantityPerUnit}
            alias:
              - name: QuantityPerUnit
                value: QuantityPerUnit
        - columnName: UnitPrice
          type: NONE
          expression:
            expressionStatement: ${UnitPrice}
            alias:
              - name: UnitPrice
                value: UnitPrice
        - columnName: UnitsInStock
          type: NONE
          expression:
            expressionStatement: ${UnitsInStock}
            alias:
              - name: UnitsInStock
                value: UnitsInStock
        - columnName: UnitsOnOrder
          type: NONE
          expression:
            expressionStatement: ${UnitsOnOrder}
            alias:
              - name: UnitsOnOrder
                value: UnitsOnOrder
        - columnName: ReorderLevel
          type: NONE
          expression:
            expressionStatement: ${ReorderLevel}
            alias:
              - name: ReorderLevel
                value: ReorderLevel
        - columnName: Discontinued
          type: NONE
          expression:
            expressionStatement: ${Discontinued}
            alias:
              - name: Discontinued
                value: Discontinued
        - columnName: CategoryName
          type: NONE
          expression:
            expressionStatement: ${CategoryName}
            alias:
              - name: CategoryName
                value: products_categories_relation--nlt$_$CategoryName
        - columnName: Description
          type: NONE
          expression:
            expressionStatement: ${Description}
            alias:
              - name: Description
                value: products_categories_relation--nlt$_$Description
        - columnName: Picture
          type: NONE
          expression:
            expressionStatement: ${Picture}
            alias:
              - name: Picture
                value: products_categories_relation--nlt$_$Picture
    fullyType2Sources: false
    checkedTreeNodesForDisplay:
      - products_categories_relation--nlt
    subtype: MODEL_BASED
    materializedSource: false
