name: products_flow
description: ''
context:
  projectId: '{{ref(project.current.projectId)}}'
  dataAppId: transform-exsn
graph: >-
  {
    "nodes": [
      {
        "type": "source",
        "id": "93c227bf-5917-455a-8de8-b789d33b0010",
        "label": "Products",
        "graphical": {
          "position": {
            "x": 80,
            "y": 40
          },
          "icon": "dataset-icon"
        },
        "handles": {
          "incoming": [],
          "outgoing": [
            {
              "id": "fcc3e390-724a-49f1-9e82-86d245025f3b",
              "type": "DEFAULT"
            }
          ]
        },
        "component": {
          "type": "qcdiDataEntitySource",
          "label": "Input dataset",
          "properties": {
            "dataEntity": {
              "projectId": "6a0073eec9225d88f9797486",
              "dataAppId": "onboarding_storage-q7fe",
              "entityId": "products-q7fh"
            },
            "configuration": {
              "name": "Products"
            }
          }
        }
      },
      {
        "type": "target",
        "id": "7f8b668e-1927-44af-9622-67abcc633fa9",
        "label": "products_flow",
        "graphical": {
          "position": {
            "x": 360,
            "y": 40
          },
          "icon": "dataset-icon"
        },
        "handles": {
          "incoming": [
            {
              "id": "9397195b-2d32-48ee-9aa4-c2295b179ef1",
              "type": "DEFAULT"
            }
          ],
          "outgoing": []
        },
        "component": {
          "type": "qcdiDataEntityTarget",
          "label": "Output dataset",
          "properties": {
            "configuration": {
              "name": "products_flow",
              "settings": {
                "materialized": "INHERIT",
                "hasHistory": "INHERIT",
                "incremental": false
              },
              "overridenColumnsConfiguration": [
                {
                  "name": "ProductID",
                  "nullable": false,
                  "primaryKeyOrdinal": 1
                },
                {
                  "name": "ProductName",
                  "nullable": false,
                  "primaryKeyOrdinal": 0
                },
                {
                  "name": "SupplierID",
                  "nullable": true,
                  "primaryKeyOrdinal": 0
                },
                {
                  "name": "CategoryID",
                  "nullable": true,
                  "primaryKeyOrdinal": 0
                },
                {
                  "name": "QuantityPerUnit",
                  "nullable": true,
                  "primaryKeyOrdinal": 0
                },
                {
                  "name": "UnitPrice",
                  "nullable": true,
                  "primaryKeyOrdinal": 0
                },
                {
                  "name": "UnitsInStock",
                  "nullable": true,
                  "primaryKeyOrdinal": 0
                },
                {
                  "name": "UnitsOnOrder",
                  "nullable": true,
                  "primaryKeyOrdinal": 0
                },
                {
                  "name": "ReorderLevel",
                  "nullable": true,
                  "primaryKeyOrdinal": 0
                },
                {
                  "name": "Discontinued",
                  "nullable": false,
                  "primaryKeyOrdinal": 0
                }
              ]
            }
          }
        }
      }
    ],
    "edges": [
      {
        "id": "b6e9bd27-afad-4e4a-8f13-fe1f2b38ef4b",
        "sourceHandle": "fcc3e390-724a-49f1-9e82-86d245025f3b",
        "targetHandle": "9397195b-2d32-48ee-9aa4-c2295b179ef1"
      }
    ]
  }
modelVersion: '1.0.0'
